<a href="https://colab.research.google.com/github/harnettd/learn-PyTorch/blob/main/00-PyTorch-Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

In [1]:
!git clone https://github.com/harnettd/learn-PyTorch.git

Cloning into 'learn-PyTorch'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 7 (delta 0), pack-reused 0
Receiving objects: 100% (7/7), done.


## Installs and Imports

In [2]:
import torch

## Defining Tensors

### Scalar

In [7]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
scalar.item()

7

### Vector

In [10]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

### Matrix

In [13]:
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 2])

## Tensor

In [16]:
TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]
    ]
])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

In [20]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.9542, 0.6059, 0.4845, 0.9388],
         [0.8517, 0.3599, 0.7182, 0.0473],
         [0.9920, 0.6504, 0.6396, 0.7607]]),
 torch.float32)

In [21]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

## Zeros and Ones

In [22]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [23]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## `arange` and like

In [25]:
v = torch.arange(0, 10)
v

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
torch.zeros_like(v)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
torch.ones_like(v)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor Datatypes

In [36]:
float_32_tensor = torch.tensor(
    [3, 6, 9],
    dtype=torch.float,
    device=None,
    requires_grad=False
)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))