<a href="https://colab.research.google.com/github/harnettd/learn-PyTorch/blob/main/00-PyTorch-Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

In [2]:
!git clone https://github.com/harnettd/learn-PyTorch.git

Cloning into 'learn-PyTorch'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 13 (delta 4), reused 5 (delta 0), pack-reused 0
Receiving objects: 100% (13/13), 6.49 KiB | 6.49 MiB/s, done.
Resolving deltas: 100% (4/4), done.


## Installs and Imports

In [1]:
import numpy as np
import random
import torch

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'device: {device}')

device: cuda


In [4]:
torch.cuda.device_count()

1

## Defining Tensors

### Scalar

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

### Vector

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

### Matrix

In [10]:
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

## Tensors

In [13]:
TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]
    ]
])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

In [16]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7120, 0.5230, 0.4773, 0.4480],
         [0.7995, 0.6309, 0.5070, 0.9845],
         [0.8242, 0.7843, 0.1188, 0.1242]]),
 torch.float32)

In [17]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

## Zeros and Ones

In [18]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [19]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## `arange` and like

In [20]:
v = torch.arange(0, 10)
v

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
torch.zeros_like(v)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
torch.ones_like(v)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor Datatypes

In [23]:
float_32_tensor = torch.tensor(
    [3, 6, 9],
    dtype=torch.float,
    device=None,
    requires_grad=False
)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

## Manipulating Tensors

In [24]:
tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor * 10

(tensor([11, 12, 13]), tensor([10, 20, 30]))

In [25]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [26]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [27]:
tensor * tensor

tensor([1, 4, 9])

In [28]:
tensor / tensor

tensor([1., 1., 1.])

In [29]:
tensor.shape

torch.Size([3])

### Matrix Multiplication

In [30]:
tensor @ tensor

tensor(14)

In [31]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [32]:
torch.transpose(tensor_B, 0, 1)

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [33]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [34]:
tensor_A @ tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [35]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [36]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## Linear Layers

In [37]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
output = linear(x)
output

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

In [38]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=3, out_features=6)
x = tensor_A.T
output = linear(x)
output

tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

## Aggregation

In [39]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
x.min(), x.max(), x.sum()

(tensor(0), tensor(90), tensor(450))

In [41]:
x.type(torch.float).mean()

tensor(45.)

In [42]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Changing Datatypes

In [43]:
y = torch.arange(0., 100., 10.)
y.dtype

torch.float32

In [44]:
z = y.type(torch.half)
z.dtype

torch.float16

In [45]:
w = z.type(torch.int8)
w, w.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8),
 torch.int8)

## Reshaping, Stacking, and Squeezing

In [46]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [50]:
y = x.reshape(1, 7)
y, y.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [49]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [51]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [53]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked.ndim, x_stacked.shape, x_stacked

(2,
 torch.Size([4, 7]),
 tensor([[5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.]]))

In [54]:
y.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7.])

## Indexing

In [55]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x.ndim, x.shape, x

(3,
 torch.Size([1, 3, 3]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [56]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [58]:
x[0, :, :], x[0, 0, :]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]))

In [59]:
x[:, :, 1]

tensor([[2, 5, 8]])

## PyTorch and NumPy

In [61]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [62]:
tensor = torch.ones(8)
array = tensor.numpy()
array, tensor

(array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1., 1.]))

## Reproducibility

In [63]:
tensor_A = torch.rand(size=(3, 4))
tensor_B = torch.rand(size=(3, 4))
tensor_A, tensor_B

(tensor([[0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090]]),
 tensor([[0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895]]))

In [68]:
SEED = 42
torch.manual_seed(seed=SEED)
torch.rand(3, 4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [69]:
torch.manual_seed(seed=SEED)
torch.rand(3, 4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

## Running Tensors on GPUs

In [5]:
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [6]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [7]:
tensor[0] = 4
tensor, tensor_on_gpu

(tensor([4, 2, 3]), tensor([1, 2, 3], device='cuda:0'))

In [9]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

## Exercises

### 2.

In [12]:
x = torch.rand(size=(7, 7))
x

tensor([[0.8321, 0.0147, 0.8859, 0.7680, 0.4398, 0.0188, 0.4739],
        [0.3210, 0.0117, 0.0927, 0.1353, 0.0228, 0.8979, 0.4715],
        [0.3150, 0.8933, 0.4742, 0.0720, 0.0671, 0.6216, 0.1101],
        [0.7791, 0.0760, 0.1412, 0.2713, 0.4344, 0.9370, 0.3448],
        [0.7587, 0.2321, 0.2107, 0.1539, 0.7543, 0.6479, 0.5668],
        [0.0951, 0.1391, 0.0923, 0.5493, 0.1276, 0.5182, 0.4349],
        [0.9786, 0.9613, 0.7633, 0.0034, 0.6311, 0.4600, 0.2018]])

### 3.

In [14]:
y = torch.rand(size=(1, 7))
y

tensor([[0.4781, 0.6686, 0.3309, 0.6989, 0.4505, 0.6594, 0.1820]])

In [15]:
y @ x

tensor([[1.8437, 0.7347, 1.0358, 1.1033, 1.0901, 2.1871, 1.3980]])

In [16]:
x @ y.T

tensor([[1.5343],
        [0.9746],
        [1.4152],
        [1.5360],
        [1.5654],
        [1.0312],
        [1.9898]])

### 4.

In [19]:
SEED = 0
torch.manual_seed(seed=SEED)
x = torch.rand(size=(7, 7))
y = torch.rand(size=(1, 7))
x, y

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]))

In [20]:
y @ x

tensor([[2.1581, 1.9307, 2.8454, 2.6230, 1.9117, 2.0266, 1.4257]])

In [21]:
x @ y.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5.

In [22]:
torch.cuda.manual_seed(seed=1234)

### 6.

In [28]:
torch.manual_seed(seed=1234)

x = torch.rand(size=(2, 3))
y = torch.rand(size=(2, 3))

x_gpu = x.to(device)
y_gpu = y.to(device)

x_gpu, y_gpu

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

### 7.

In [32]:
x_gpu.shape, y_gpu.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [34]:
tensor_A = x_gpu @ y_gpu.T
tensor_A

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [35]:
tensor_B = x_gpu.T @ y_gpu
tensor_B

tensor([[0.1230, 0.3009, 0.2260],
        [0.0401, 0.2338, 0.3036],
        [0.2457, 0.6707, 0.5696]], device='cuda:0')

### 8.

In [37]:
tensor_B.min(), tensor_B.max()

(tensor(0.0401, device='cuda:0'), tensor(0.6707, device='cuda:0'))

### 9.

In [38]:
tensor_B.argmin(), tensor_B.argmax()

(tensor(3, device='cuda:0'), tensor(7, device='cuda:0'))

### 10.

In [43]:
torch.manual_seed(seed=7)
z = torch.rand(size=(1, 1, 1, 10))
z, z.squeeze()

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))